const bibleVersions = {
"KJ21" : "21st Century King James Version (KJ21)",
"ASV" : "American Standard Version (ASV)",
"AMP" : "Amplified Bible (AMP)",
"AMPC" : "Amplified Bible, Classic Edition (AMPC)",
"BRG" : "BRG Bible (BRG)",
"CSB" : "Christian Standard Bible (CSB)",
"CEB" : "Common English Bible (CEB)",
"CJB" : "Complete Jewish Bible (CJB)",
"CEV" : "Contemporary English Version (CEV)",
"DARBY" : "Darby Translation (DARBY)",
"DLNT" : "Disciples’ Literal New Testament (DLNT)",
"DRA" : "Douay-Rheims 1899 American Edition (DRA)",
"ERV" : "Easy-to-Read Version (ERV)",
"EHV" : "Evangelical Heritage Version (EHV)",
"ESV" : "English Standard Version (ESV)",
"ESVUK" : "English Standard Version Anglicised (ESVUK)",
"EXB" : "Expanded Bible (EXB)",
"GNV" : "1599 Geneva Bible (GNV)",
"GW" : "GOD’S WORD Translation (GW)",
"GNT" : "Good News Translation (GNT)",
"HCSB" : "Holman Christian Standard Bible (HCSB)",
"ICB" : "International Children’s Bible (ICB)",
"ISV" : "International Standard Version (ISV)",
"PHILLIPS" : "J.B. Phillips New Testament (PHILLIPS)",
"JUB" : "Jubilee Bible 2000 (JUB)",
"KJV" : "King James Version (KJV)",
"AKJV" : "Authorized (King James) Version (AKJV)",
"LEB" : "Lexham English Bible (LEB)",
"TLB" : "Living Bible (TLB)",
"MSG" : "The Message (MSG)",
"MEV" : "Modern English Version (MEV)",
"MOUNCE" : "Mounce Reverse Interlinear New Testament (MOUNCE)",
"NOG" : "Names of God Bible (NOG)",
"NABRE" : "New American Bible (Revised Edition) (NABRE)",
"NASB" : "New American Standard Bible (NASB)",
"NASB1995" : "New American Standard Bible 1995 (NASB1995)",
"NCB" : "New Catholic Bible (NCB)",
"NCV" : "New Century Version (NCV)",
"NET" : "New English Translation (NET)",
"NIRV" : "New International Reader's Version (NIRV)",
"NIV"  : "New International Version (NIV)",
"NIVUK" : "New International Version - UK (NIVUK)",
"NKJV" : "New King James Version (NKJV)",
"NLV" : "New Life Version (NLV)",
"NLT" : "New Living Translation (NLT)",
"NMB" : "New Matthew Bible (NMB)",
"NRSV" : "New Revised Standard Version (NRSV)",
"NRSVA" : "New Revised Standard Version, Anglicised (NRSVA)",
"NRSVACE" : "New Revised Standard Version, Anglicised Catholic Edition (NRSVACE)",
"NRSVCE" : "New Revised Standard Version Catholic Edition (NRSVCE)",
"NTE" : "New Testament for Everyone (NTE)",
"OJB" : "Orthodox Jewish Bible (OJB)",
"TPT" : "The Passion Translation (TPT)",
"RGT" : "Revised Geneva Translation (RGT)",
"RSV" : "Revised Standard Version (RSV)",
"RSVCE" : "Revised Standard Version Catholic Edition (RSVCE)",
"TLV" : "Tree of Life Version (TLV)",
"VOICE" : "The Voice (VOICE)",
"WEB" : "World English Bible (WEB)",
"WE" : "Worldwide English (New Testament) (WE)",
"WYC" : "Wycliffe Bible (WYC)",
"YLT" : "Young's Literal Translation (YLT)"
};